
package guisimexp;

import java.awt.TextArea;
import java.awt.*;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import jess.*;
import jess.awt.TextAreaWriter;
/**
 *
 * @author Donatto
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form System
     */
    public Interfaz() {
        initComponents();
        setLocationRelativeTo(null);
        cargar_file();
    }
    
    public static Rete motor;
    
    public void cargar_file(){
        motor = new Rete();
        try {
            motor.batch("C:\\Users\\OFFICE\\Documents\\NetBeansProjects\\GUISimExp\\src\\guisimexp\\BCR.clp");
        } catch (JessException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CBExtremidades = new javax.swing.JComboBox<>();
        CBAltura = new javax.swing.JComboBox<>();
        CBEstrucOsea = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CBCapAumneto = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        CBEnergia = new javax.swing.JComboBox<>();
        CBGrasa = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        CBPeso = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextareaSalida = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gimnasio Alvarez");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de cuerpo"));

        jLabel1.setText("Estructura Fisica");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Estructura Osea:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Altura:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Extremidades:");

        CBExtremidades.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CBExtremidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cortas ", "Medias ", "Largas" }));
        CBExtremidades.setName("CBExtremidades"); // NOI18N

        CBAltura.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CBAltura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baja", "Media ", "Alta" }));
        CBAltura.setName("CBAltura"); // NOI18N

        CBEstrucOsea.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CBEstrucOsea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rolliza ", "Delgada ", "Atletica" }));
        CBEstrucOsea.setName("CBEstrucOsea"); // NOI18N

        jLabel5.setText("Metabolismo");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Capacidad de Aumneto:");

        CBCapAumneto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CBCapAumneto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Minima ", "Media ", "Alta" }));
        CBCapAumneto.setName("CBCapAumento"); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Energia:");

        CBEnergia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CBEnergia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baja", "Media ", "Alta" }));
        CBEnergia.setName("CBEnergia"); // NOI18N

        CBGrasa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CBGrasa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Minima", "Suficiente ", "Mucha " }));
        CBGrasa.setName("CbGrasa"); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Grasa en el cuerpo:");

        CBPeso.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CBPeso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ligero", "Medio ", "Alto" }));
        CBPeso.setName("CBPeso"); // NOI18N

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Peso de la persona:");

        jLabel10.setText("Cuerpo de la Persona");

        jButton1.setText("Conocer Tipo de Cuerpo");
        jButton1.setName("btnConocer"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextareaSalida.setColumns(20);
        jTextareaSalida.setRows(5);
        jScrollPane1.setViewportView(jTextareaSalida);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CBEstrucOsea, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CBAltura, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(54, 54, 54))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(CBPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(37, 37, 37)
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(CBGrasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(CBCapAumneto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(37, 37, 37)
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(CBEnergia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(403, 403, 403)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CBExtremidades, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(CBExtremidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBEstrucOsea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(CBEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBCapAumneto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(CBGrasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String estrucOsea =(String) this.CBEstrucOsea.getSelectedItem();
        String altura, extremidades, mensaje ="", instruccion, instruccion2, instruccion3, capAumento, energia, peso, grasa;
        altura = (String) this.CBAltura.getSelectedItem();
        extremidades = (String) this.CBExtremidades.getSelectedItem();
        capAumento = (String) this.CBCapAumneto.getSelectedItem();
        energia = (String) this.CBEnergia.getSelectedItem();
        peso = (String) this.CBPeso.getSelectedItem();
        grasa = (String) this.CBGrasa.getSelectedItem();
        
        instruccion = "(estructura (osea "+ estrucOsea +" )(altura "+ altura +")(extremidades "+extremidades+"))"; 
        instruccion2 = "(metabolismo (capacidad_aumento "+capAumento+")(energia "+energia+"))";
        instruccion3 = "(cuerpo (peso "+peso+")(grasa "+grasa+"))";
        String completa = instruccion + instruccion2 + instruccion3;
        
        //JOptionPane.showMessageDialog(rootPane,mensaje,"INFORMATION", JOptionPane.INFORMATION_MESSAGE);
        try {
            motor.assertString(completa);
            //motor.assertString(instruccion2);
            //motor.assertString(instruccion3);
            
            motor.run();
            
            Iterator it = motor.listFacts();
            
            TextArea ta = new TextArea(20, 80);
            TextAreaWriter taw = new TextAreaWriter(ta);
            
            while(it.hasNext()){
                Fact facts = (Fact)it.next();
                mensaje = mensaje +","+ facts.getName();
                this.jTextareaSalida.setText(mensaje);
                //JOptionPane.showMessageDialog(rootPane, mensaje, "Information", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (JessException e) {
            e.printStackTrace();
        }
        
       /* try {
            motor.executeCommand("(facts)");
        } catch (JessException e) {
            e.printStackTrace();
        }*/           
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBAltura;
    private javax.swing.JComboBox<String> CBCapAumneto;
    private javax.swing.JComboBox<String> CBEnergia;
    private javax.swing.JComboBox<String> CBEstrucOsea;
    private javax.swing.JComboBox<String> CBExtremidades;
    private javax.swing.JComboBox<String> CBGrasa;
    private javax.swing.JComboBox<String> CBPeso;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextareaSalida;
    // End of variables declaration//GEN-END:variables
}
